import { NgModule } from '@angular/core';
import {
  MatCardModule,
  MatExpansionModule,
  MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatSelectModule,
  MatSidenavModule,
  MatListModule,
  MatMenuModule,
  MatToolbarModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatStepperModule,
  MatRadioModule,
  MatBadgeModule,
  MatTabsModule,
  MatCheckboxModule,
  MatTableModule,
  MatDialogModule,
  MatDividerModule,
  MatTooltipModule,
  /*
  MatAutocompleteModule,
  MatBottomSheetModule,

  MatChipsModule,
  MatDatepickerModule,
  MatListModule,
  MatMenuModule,
  MatNativeDateModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatRippleModule,
  MatSidenavModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatSnackBarModule,
  MatSortModule,

  MatTabsModule,
  MatTreeModule, */
} from '@angular/material';


@NgModule({
  imports: [
    MatCardModule,
    MatExpansionModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatSelectModule,
    MatSidenavModule,
    MatListModule,
    MatMenuModule,
    MatToolbarModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatStepperModule,
    MatRadioModule,
    MatBadgeModule,
    MatTabsModule,
    MatCheckboxModule,
    MatTooltipModule,
    MatDialogModule,
    MatDividerModule,
    MatTableModule,

  ],
  exports: [
    MatCardModule,
    MatExpansionModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatSelectModule,
    MatSidenavModule,
    MatListModule,
    MatMenuModule,
    MatToolbarModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatStepperModule,
    MatRadioModule,
    MatBadgeModule,
    MatTabsModule,
    MatCheckboxModule,
    MatTooltipModule,
    MatDialogModule,
    MatDividerModule,
    MatTableModule,
  ]
})
export class MaterialModule { }
